### ISSUE TITLE
Tool definitions under jupyter kernel server

### ISSUE THREAD

**Issue by ray-tam-appier** [xingyaoww/code-act#6]
Hi I notice there's a tools_to_run code in jupyterkernel server [this line](https://github.com/xingyaoww/code-act/blob/main/scripts/chat/code_execution/jupyter.py#L76). However there's no documentation on how to define one.

How does each code tool code should looks like? can i just paste in tool code under mint/tools and update the system prompt?

**Comment by xingyaoww** [comment]
Thanks for your interests!

Yes! You can just paste in arbitrary function definition as a string, for example:

```python
import math

def foo(a):
    return math.ceil(a)
```

Something like this, then your agent will be able to access this `foo` function in its `<execute>` environments.

Feel free to re-open this issue if you have any further questions!
